// Class Engine.SceneComponent
ComponentVelocity	=	0x290,//(0xC)
// Class Engine.SceneComponent
RelativeLocation	=	0x29C,//(0xC)
// Class Engine.SceneComponent
RelativeRotation	=	0x2D0,//(0xC)
// Class Engine.PrimitiveComponent
LastRenderTime	=	0x77C,//(0x4)
// UNKNOWN PROPERTY: EncryptedObjectProperty Engine.Actor.RootComponent
RootComponent	=	0x288,//(0x8)
// UNKNOWN PROPERTY: EncryptedObjectProperty Engine.Pawn.PlayerState
PlayerState	=	0x448,//(0x8)
// Class Engine.PlayerController
PlayerCameraManager	=	0x4B8,//(0x8)
// Class Engine.Character
Mesh	=	0x568,//(0x8)
// Class Engine.CharacterMovementComponent
MaxAcceleration	=	0x318,//(0x4)
// Class Engine.CharacterMovementComponent
Acceleration	=	0x3B8,//(0xC)
// Class Engine.CharacterMovementComponent
LastUpdateVelocity	=	0x3E0,//(0xC)
// Class Engine.PlayerCameraManager
CameraCache	=	0x420,//(0x5D0)
// Class Engine.SkeletalMeshComponent
AnimScriptInstance	=	0xC90,//(0x8)
// UNKNOWN PROPERTY: EncryptedObjectProperty Engine.World.CurrentLevel
CurrentLevel	=	0x990,//(0x8)
// ScriptStruct Engine.MinimalViewInfo
Rotation	=	0x14,//(0xC)
// ScriptStruct Engine.MinimalViewInfo
FOV	=	0x30,//(0x4)
// ScriptStruct Engine.MinimalViewInfo
Location	=	0x5B0,//(0xC)
// ScriptStruct Engine.CameraCacheEntry
POV	=	0x10,//(0x5C0)
// Class TslGame.TslCharacter
WeaponProcessor	=	0xD28,//(0x8)
// Class TslGame.TslCharacter
Health	=	0xD88,//(0x4)
// Class TslGame.TslCharacter
LastTeamNum	=	0x17A0,//(0x4)
// Class TslGame.TslCharacter
CharacterName	=	0x17B0,//(0x10)
// Class TslGame.TslCharacter
SpectatedCount	=	0x19D0,//(0x4)
// Class TslGame.TslCharacter
GroggyHealth	=	0x1F64,//(0x4)
// Class TslGame.WeaponTrajectoryData
RecoilConfig	=	0x48,//(0xD8)
// Class TslGame.WeaponTrajectoryData
TrajectoryConfig	=	0x120,//(0x48)
// Class TslGame.TslWeapon_Trajectory
WeaponTrajectoryData	=	0x1000,//(0x8)
// Class TslGame.DroppedItemInteractionComponent
Item	=	0x660,//(0x8)
// UNKNOWN PROPERTY: EncryptedObjectProperty TslGame.DroppedItem.Item
Item	=	0x430,//(0x8)
// Class TslGame.WeaponProcessorComponent
EquippedWeapons	=	0x2C8,//(0x10)
// Class TslGame.WeaponProcessorComponent
WeaponArmInfo	=	0x2E8,//(0x5)
// ScriptStruct TslGame.ItemTableRowBase
ProjectileConfig	=	0xB0,//(0x20)
// ScriptStruct TslGame.ItemTableRowBase
ItemID	=	0x248,//(0x8)
// Class AIModule.CrowdFollowingComponent
CharacterMovement	=	0x4F0,//(0x8)
