// Class Engine.SceneComponent
RelativeRotation	=	0x24C,//(0xC)
// Class Engine.SceneComponent
ComponentVelocity	=	0x380,//(0xC)
// Class Engine.PlayerController
PlayerCameraManager	=	0x4B0,//(0x8)
// Class Engine.Character
Mesh	=	0x468,//(0x8)
// UNKNOWN PROPERTY: EncryptedObjectProperty Engine.World.CurrentLevel
CurrentLevel	=	0x978,//(0x8)
// Class Engine.SkeletalMeshComponent
AnimScriptInstance	=	0xC90,//(0x8)
// Class Engine.PlayerCameraManager
CameraCache	=	0x440,//(0x5D0)
// Class Engine.CharacterMovementComponent
MaxAcceleration	=	0x318,//(0x4)
// Class Engine.CharacterMovementComponent
Acceleration	=	0x3B8,//(0xC)
// Class Engine.CharacterMovementComponent
LastUpdateVelocity	=	0x3E0,//(0xC)
// ScriptStruct Engine.MinimalViewInfo
Location	=	0x0,//(0xC)
// ScriptStruct Engine.MinimalViewInfo
Rotation	=	0xC,//(0xC)
// ScriptStruct Engine.MinimalViewInfo
FOV	=	0x5B0,//(0x4)
// Class TslGame.TslCharacter
CharacterName	=	0xD88,//(0x10)
// Class TslGame.TslCharacter
SpectatedCount	=	0xE30,//(0x4)
// Class TslGame.TslCharacter
WeaponProcessor	=	0xF60,//(0x8)
// Class TslGame.TslCharacter
Health	=	0x10E0,//(0x4)
// Class TslGame.TslCharacter
LastTeamNum	=	0x17D8,//(0x4)
// Class TslGame.TslCharacter
GroggyHealth	=	0x1814,//(0x4)
// Class TslGame.WeaponTrajectoryData
RecoilConfig	=	0x48,//(0xD8)
// Class TslGame.WeaponTrajectoryData
TrajectoryConfig	=	0x120,//(0x48)
// Class TslGame.TslWeapon_Trajectory
WeaponTrajectoryData	=	0x1000,//(0x8)
// Class TslGame.DroppedItemInteractionComponent
Item	=	0x660,//(0x8)
// Class TslGame.WeaponProcessorComponent
EquippedWeapons	=	0x2C8,//(0x10)
// Class TslGame.WeaponProcessorComponent
WeaponArmInfo	=	0x2E8,//(0x5)
// UNKNOWN PROPERTY: EncryptedObjectProperty TslGame.DroppedItem.Item
Item	=	0x428,//(0x8)
// Class AIModule.CrowdFollowingComponent
CharacterMovement	=	0x4F0,//(0x8)
