// Class Engine.SceneComponent
RelativeRotation	=	0x2F8,//(0xC)
// Class Engine.SceneComponent
ComponentVelocity	=	0x370,//(0xC)
// Class Engine.PlayerController
PlayerCameraManager	=	0x4B8,//(0x8)
// Class Engine.Character
Mesh	=	0x560,//(0x8)
// Class Engine.CharacterMovementComponent
MaxAcceleration	=	0x318,//(0x4)
// Class Engine.CharacterMovementComponent
Acceleration	=	0x3B8,//(0xC)
// Class Engine.CharacterMovementComponent
LastUpdateVelocity	=	0x3E0,//(0xC)
// Class Engine.PlayerCameraManager
CameraCache	=	0x1610,//(0x5D0)
// Class Engine.SkeletalMeshComponent
AnimScriptInstance	=	0xCA0,//(0x8)
// ScriptStruct Engine.MinimalViewInfo
Rotation	=	0xC,//(0xC)
// ScriptStruct Engine.MinimalViewInfo
FOV	=	0x5A4,//(0x4)
// ScriptStruct Engine.MinimalViewInfo
Location	=	0x5AC,//(0xC)
// Class TslGame.TslCharacter
SpectatedCount	=	0xA4C,//(0x4)
// Class TslGame.TslCharacter
WeaponProcessor	=	0xDE8,//(0x8)
// Class TslGame.TslCharacter
GroggyHealth	=	0xF6C,//(0x4)
// Class TslGame.TslCharacter
Health	=	0x10B4,//(0x4)
// Class TslGame.TslCharacter
CharacterName	=	0x11F0,//(0x10)
// Class TslGame.TslCharacter
LastTeamNum	=	0x1870,//(0x4)
// Class TslGame.WeaponProcessorComponent
EquippedWeapons	=	0x2C8,//(0x10)
// Class TslGame.WeaponProcessorComponent
WeaponArmInfo	=	0x2E8,//(0x5)
// Class TslGame.WeaponTrajectoryData
RecoilConfig	=	0x48,//(0xD8)
// Class TslGame.WeaponTrajectoryData
TrajectoryConfig	=	0x120,//(0x48)
// Class TslGame.TslWeapon_Trajectory
WeaponTrajectoryData	=	0x1000,//(0x8)
// Class TslGame.DroppedItemInteractionComponent
Item	=	0x670,//(0x8)
// Class AIModule.CrowdFollowingComponent
CharacterMovement	=	0x4F0,//(0x8)
