// UNKNOWN PROPERTY: EncryptedObjectProperty Engine.Actor.RootComponent
RootComponent	=	0x3D0,//(0x8)
// Class Engine.SceneComponent
RelativeRotation	=	0x200,//(0xC)
// Class Engine.SceneComponent
ComponentVelocity	=	0x248,//(0xC)
// Class Engine.SceneComponent
RelativeLocation	=	0x2D0,//(0xC)
// Class Engine.PrimitiveComponent
LastRenderTime	=	0x78C,//(0x4)
// Class Engine.SkeletalMeshComponent
AnimScriptInstance	=	0xCA0,//(0x8)
// UNKNOWN PROPERTY: EncryptedObjectProperty Engine.Pawn.PlayerState
PlayerState	=	0x430,//(0x8)
// Class Engine.PlayerController
PlayerCameraManager	=	0x4A0,//(0x8)
// Class Engine.Character
Mesh	=	0x4A8,//(0x8)
// Class Engine.CharacterMovementComponent
MaxAcceleration	=	0x308,//(0x4)
// Class Engine.CharacterMovementComponent
Acceleration	=	0x3A8,//(0xC)
// Class Engine.CharacterMovementComponent
LastUpdateVelocity	=	0x3D0,//(0xC)
// Class Engine.PlayerCameraManager
CameraCache	=	0xA00,//(0x5D0)
// UNKNOWN PROPERTY: EncryptedObjectProperty Engine.World.CurrentLevel
CurrentLevel	=	0x970,//(0x8)
// ScriptStruct Engine.MinimalViewInfo
Rotation	=	0xC,//(0xC)
// ScriptStruct Engine.MinimalViewInfo
Location	=	0x28,//(0xC)
// ScriptStruct Engine.MinimalViewInfo
FOV	=	0x5B4,//(0x4)
// ScriptStruct Engine.CameraCacheEntry
POV	=	0x10,//(0x5C0)
// Class TslGame.WeaponProcessorComponent
EquippedWeapons	=	0x2B8,//(0x10)
// Class TslGame.WeaponProcessorComponent
WeaponArmInfo	=	0x2D8,//(0x5)
// Class TslGame.TslCharacter
GroggyHealth	=	0xEA4,//(0x4)
// Class TslGame.TslCharacter
CharacterName	=	0xF88,//(0x10)
// Class TslGame.TslCharacter
Health	=	0x1030,//(0x4)
// Class TslGame.TslCharacter
WeaponProcessor	=	0x1140,//(0x8)
// Class TslGame.TslCharacter
LastTeamNum	=	0x1858,//(0x4)
// Class TslGame.TslCharacter
SpectatedCount	=	0x1968,//(0x4)
// Class TslGame.WeaponTrajectoryData
RecoilConfig	=	0x40,//(0xD8)
// Class TslGame.WeaponTrajectoryData
TrajectoryConfig	=	0x118,//(0x48)
// Class TslGame.TslWeapon_Trajectory
WeaponTrajectoryData	=	0x1010,//(0x8)
// Class TslGame.DroppedItemInteractionComponent
Item	=	0x670,//(0x8)
// UNKNOWN PROPERTY: EncryptedObjectProperty TslGame.DroppedItem.Item
Item	=	0x418,//(0x8)
// ScriptStruct TslGame.ItemTableRowBase
ProjectileConfig	=	0xB0,//(0x20)
// ScriptStruct TslGame.ItemTableRowBase
ItemID	=	0x248,//(0x8)
// Class AIModule.CrowdFollowingComponent
CharacterMovement	=	0x4E0,//(0x8)
